import { Template } from '../types';

export const templates: Template[] = [
  {
    id: 'saas-landing',
    name: 'SaaS Landing Page',
    category: 'SaaS',
    description: 'Modern landing page for software products with pricing, features, and testimonials.',
    prompt: 'Create a modern SaaS landing page for an AI-powered analytics startup called DataFlow. Include hero, features, pricing, testimonials, FAQ, and CTA sections. Use a clean modern style.',
    preview: '🚀',
  },
  {
    id: 'restaurant',
    name: 'Restaurant Website',
    category: 'Restaurant',
    description: 'Elegant restaurant website with menu, gallery, and reservation system.',
    prompt: 'Create an elegant restaurant website for an Indian fine dining restaurant called Saffron Kitchen. Include hero, about, menu highlights, gallery, testimonials, and contact sections.',
    preview: '🍽️',
  },
  {
    id: 'portfolio',
    name: 'Developer Portfolio',
    category: 'Portfolio',
    description: 'Clean portfolio for software developers and designers.',
    prompt: 'Create a portfolio website for a senior software engineer named Alex Chen. Include hero, about, services, projects gallery, testimonials, and contact sections. Modern minimal style.',
    preview: '💻',
  },
  {
    id: 'ecommerce',
    name: 'E-commerce Store',
    category: 'E-commerce',
    description: 'Product-focused store with collections and shopping features.',
    prompt: 'Create an e-commerce website for a luxury women\'s footwear brand called Zivbelle. Include hero, featured products, about, testimonials, newsletter, and footer. Premium luxury style.',
    preview: '👠',
  },
  {
    id: 'agency',
    name: 'Creative Agency',
    category: 'Agency',
    description: 'Professional agency website showcasing services and team.',
    prompt: 'Create a creative agency website for a design studio called Pixel Studio. Include hero, services, about, team, testimonials, and CTA sections. Bold creative style.',
    preview: '🎨',
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    category: 'Real Estate',
    description: 'Property listing website with featured homes and agent profiles.',
    prompt: 'Create a real estate website for luxury properties called Prestige Homes. Include hero, featured properties, stats, testimonials, and contact sections. Elegant professional style.',
    preview: '🏠',
  },
  {
    id: 'education',
    name: 'Online Course Platform',
    category: 'Education',
    description: 'Education platform with courses, pricing, and student testimonials.',
    prompt: 'Create an online education platform website called LearnHub. Include hero, features, pricing plans, testimonials, FAQ, and CTA sections. Modern clean style.',
    preview: '📚',
  },
  {
    id: 'blog',
    name: 'Personal Blog',
    category: 'Blog',
    description: 'Clean blog layout with newsletter signup and featured posts.',
    prompt: 'Create a personal blog website called The Daily Digest. Include hero, featured articles, newsletter signup, and footer. Minimal clean style.',
    preview: '✍️',
  },
  {
    id: 'healthcare',
    name: 'Healthcare Clinic',
    category: 'Healthcare',
    description: 'Professional medical clinic website with services and booking.',
    prompt: 'Create a healthcare clinic website called MediCare Plus. Include hero, services, about, team, testimonials, and contact sections. Professional trustworthy style.',
    preview: '🏥',
  },
  {
    id: 'event',
    name: 'Event Planning',
    category: 'Event',
    description: 'Event planning company website with portfolio and packages.',
    prompt: 'Create an event planning website called Grand Celebrations. Include hero, services, gallery, testimonials, pricing, and contact sections. Elegant festive style.',
    preview: '🎉',
  },
  {
    id: 'startup',
    name: 'Tech Startup',
    category: 'SaaS',
    description: 'Dynamic startup landing page with product showcase.',
    prompt: 'Create a tech startup website for an AI company called NexGen AI. Include hero, features, stats, pricing, testimonials, and CTA. Modern bold style.',
    preview: '⚡',
  },
  {
    id: 'fashion',
    name: 'Fashion Brand',
    category: 'E-commerce',
    description: 'Luxury fashion brand website with collections.',
    prompt: 'Create a fashion brand website for a luxury clothing line called Elegance. Include hero, products, about, testimonials, newsletter, and CTA. Luxury elegant style.',
    preview: '👗',
  },
];

export const examplePrompts = [
  'SaaS Landing Page',
  'Restaurant Website',
  'Portfolio',
  'E-commerce Store',
  'Agency Website',
  'Blog',
  'Startup',
  'Personal Website',
];
